### ISSUE TITLE
focusPath is undefined

### ISSUE THREAD

**Issue by iamkevingreen** [azzlack/sanity-plugin-tabs#11]
```
Warning: Failed prop type: The prop `focusPath` is marked as required in `Tabs`, but its value is `undefined`.
```

I'm on the latest and greatest sanity-plugin-tabs + latest and greatest sanity:
```
    "@sanity/base": "^1.149.8",
    "@sanity/cli": "^1.149.9",
    "@sanity/color-input": "^1.149.7",
    "@sanity/components": "^1.149.8",
    "@sanity/core": "^1.149.9",
    "@sanity/default-layout": "^1.149.8",
    "@sanity/default-login": "^1.149.7",
    "@sanity/desk-tool": "^1.149.8",
```

Issue occurred after updating the studio. Now only my last tab is active/visible, no way to see the other content in the tabs aside from arrange them in dev as a temp fix. 

I just reverted my Sanity studio so that it continues to work.

My Working configuration:

```
    "@sanity/base": "1.148.5",
    "@sanity/cli": "1.148.6",
    "@sanity/color-input": "1.148.1",
    "@sanity/components": "1.148.5",
    "@sanity/core": "1.148.5",
    "@sanity/default-layout": "1.148.5",
    "@sanity/default-login": "1.148.1",
    "@sanity/desk-tool": "1.148.6",
    "sanity-plugin-tabs": "1.1.2",
```

I realize 1.1.2 is  a few versions back but it does work :)

Let me know if there is anything else I can provide, I may also have time run it locally to see if I can figure out what's happening.

Additionally my [studio is open source](https://github.com/ctrl-alt-del-world/midway/tree/0ff08201d4470a1a22e094f9b81ae6c0f7db0c40/studio)!

**Comment by blimpmason** [comment]
+1

**Comment by alexhhn** [comment]
+1
