### ISSUE TITLE
Input errors are not displayed locally

### ISSUE THREAD

**Issue by clementoriol** [azzlack/sanity-plugin-tabs#15]
(Using up to date sanity libraries (1.149.17) and sanity-plugin-tabs@1.1.8)

When using tabs, the error display is broken on inputs.
Errors are properly displayed on the top-right indicator but the inputs are not highlighted properly.

Current behavior: 
<img width="939" alt="Capture d'écran 2020-07-01 16 44 08" src="https://user-images.githubusercontent.com/3337108/86257700-36726800-bbba-11ea-8c68-1c177d200746.png">

Expected behavior:
<img width="943" alt="Capture d'écran 2020-07-01 16 43 17" src="https://user-images.githubusercontent.com/3337108/86257724-3bcfb280-bbba-11ea-82e1-ae8463b92310.png">

For what I gathered it looks like when tab markers are built the path is wrong for some reason.
I pinpointed the issue, and apparently it comes from the trimming of child paths :

broken:
```
  getFieldMarkers = (fieldName) => {
    return this.props.markers
      .filter((marker) => PathUtils.startsWith([fieldName], marker.path))
      .map((marker) => ({
        ...marker,
        path: this.trimChildPath([fieldName], marker.path),
      }));
  };
```

works:
```
getFieldMarkers = (fieldName) => {
    return this.props.markers.filter((marker) =>
      PathUtils.startsWith([fieldName], marker.path)
    );
  };
```

However I'm a bit confused about why this trimming was happening in the first place. Legacy code from an older version maybe? I'm just starting to grasp sanity's custom components, so I'd love any input on this.

I can submit a PR anytime.

**Comment by isaac-martin** [comment]
Mmm just came across this in my project running tabs @ `1.2.0` anyone else seen a regression?

**Comment by spacedawwwg** [comment]
I've just come to report this as an issue (using sanity-plugin-tabs v2.0.0)

I wonder if a change in Sanity 2.x has caused this maybe?

**Comment by azzlack** [comment]
@spacedawwwg Will look into this
