### ISSUE TITLE
Using the same tabs across objects

### ISSUE THREAD

**Issue by LouiseEH** [azzlack/sanity-plugin-tabs#23]
Hi,

I want to use this plugin for making a number of tabs, lets call them T1, T2 and T3.
The structure of the schemas are as follows:

1. Document X which has an object A and an object B, each object defined with "inputComponent: Tabs,"
2. Document Y which has an object A and an object C, each object defined with "inputComponent: Tabs,"
3. Document Z which has an object A, C and D, each object defined with "inputComponent: Tabs,"

I want the fields defined in objects A, B, C and D spread across the tabs, e.g. some fields from each object A, B, C and D on T1, some fields from each object on T2 etc.
My approach was to define the same fieldsets on all the object levels, but instead of having the fields gathered on the same tabs,  I get a list of the objects with their own tabs, such that the tabs are shown multiple times.

I believe I can get the setup I want, by listing the fields on the document level, but that would mean I have to duplicate the fields in e.g. object A on both document X, Y and Z, which maintenance-wize is not optimal. 

Is there a way to be able to re-use the objects and get the fields from different objects on the same tabs?

**Comment by azzlack** [comment]
I dont think that is possible with the current version because of the wait it uses the Sanity document structure.
However, we could maybe create an option field where you can specify what props you would like to show in the Tab. There could be some issues with duplicate fields though - will have to test that

**Comment by LouiseEH** [comment]
@azzlack Ok, I am relatively new to both node.js and Sanity, so I am curious as to how that would look like. Would you define the options in the definition of the document, i.e.:
`"inputComponents: Tabs{ options: ["object_a.field1", "object_a.field5"]}"`

Is the potential problem with duplicate fields if e.g. object A and B both have a field named "title"?

**Comment by LouiseEH** [comment]
I'll close the issue as I am not skilled enough to implement the change myself. I structured by tabs in a different way
