### ISSUE TITLE
Misaligned text when error icons are visible

### ISSUE THREAD

**Issue by spacedawwwg** [azzlack/sanity-plugin-tabs#26]
![image](https://user-images.githubusercontent.com/1691867/97361508-8a0a6f00-1897-11eb-82fd-14d2496fd2fa.png)

Would also be better to use the same error icon as sanity (circled warning in red)

**Comment by azzlack** [comment]
This is awesome, will release this asap :-)

**Comment by spacedawwwg** [comment]
Fixed in https://github.com/azzlack/sanity-plugin-tabs/pull/27
