### ISSUE TITLE
Plugin appears to be incompatible with Sanity v2.1.x

### ISSUE THREAD

**Issue by nboliver** [azzlack/sanity-plugin-tabs#28]
Upgrading Sanity to v2.1.x causes the desk to crash when changing tabs.

**Comment by mornir** [comment]
Hi!
I've been using this plugin with Sanity v2.1.x and didn't have any problem.
What error do you get in the console?

**Comment by DevinEdwards** [comment]
@nboliver I was getting an error as well:

`Uncaught TypeError: Cannot read property 'sanity' of undefined`

I remove my `.lock` file and `node_modules` folder. And did a fresh `yarn install` and it seemed to clear up the issue. Not sure exactly why this was happening though.

**Comment by hessius** [comment]
I am encountering the same error, @DevinEdwards and can confirm I got it working with your fix, although it took a few attempts... I had initially run sanity install, deleted the node_modules and package-lock.json, reran package installation with yarn but with the same result, deleted node_modules and yarn.lock and reran sanity install and presto!
