### ISSUE TITLE
Editing Arrays and bodies is broken

### ISSUE THREAD

**Issue by tom2strobl** [azzlack/sanity-plugin-tabs#5]
I'm sorry for being super vage, but I'm kinda in a hurry right now so I can't investigate deeply, but wanted to report nevertheless. After some `sanity upgrade` business some fields including body block annotations and an `Array` of `references`  stopped working, so I had to disable the Tabs input component (just commented out the `inputComponent = Tabs` basically), which makes everything work again.

See this quick clip for example:
[sanity-tabs-issue.mov.zip](https://github.com/azzlack/sanity-plugin-tabs/files/4268029/sanity-tabs-issue.mov.zip)

**Comment by Laurent-PANEK** [comment]
Hello,

I encounter the same issue as @tom2strobl 

After few investigations, it seems that the latest release, version `1.1.4`, as broke down any fields of type `array`.

The modal which open on change isn't trigger anymore, or at least isn't display on the screen, as a result you can't add new value or edit existing values.

As workaround, I pinned the plugin version to `1.1.3`.

Gladly appreciate your help to fix this issue.
